# Generated by Django 5.1.2 on 2024-10-08 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('first_name_en', models.CharField(max_length=64, null=True, verbose_name='First Name')),
                ('first_name_uz', models.CharField(max_length=64, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('last_name_en', models.CharField(max_length=64, null=True, verbose_name='Last Name')),
                ('last_name_uz', models.CharField(max_length=64, null=True, verbose_name='Last Name')),
                ('profession', models.CharField(max_length=64, verbose_name='Profession')),
                ('profession_en', models.CharField(max_length=64, null=True, verbose_name='Profession')),
                ('profession_uz', models.CharField(max_length=64, null=True, verbose_name='Profession')),
                ('avatar', models.ImageField(upload_to='team/', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Organization Name')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='Location')),
                ('linkedin_link', models.CharField(blank=True, max_length=64, null=True, verbose_name='Linkedin')),
                ('avatar', models.ImageField(upload_to='users/', verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
