# Generated by Django 5.1.2 on 2024-10-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammodel',
            name='first_name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='last_name_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='teammodel',
            name='profession_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='Profession'),
        ),
    ]
