# Generated by Django 5.1.2 on 2024-10-08 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teammodel_first_name_ru_teammodel_last_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='teammodel',
            name='last_name_uz',
        ),
    ]
