version: "3.9"

services:
  web:
    build: .
    container_name: exam6_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: exam6_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01012008
      POSTGRES_DB: exam_6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
