# Generated by Django 5.1.2 on 2024-10-19 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentoffermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentproblemmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecommentoffermodel',
            name='offer_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.commentoffermodel'),
        ),
        migrations.AddField(
            model_name='likecommentoffermodel',
            name='user',
            field=models.ManyToManyField(related_name='like_comment_offer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecommentproblemmodel',
            name='problem_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.commentproblemmodel'),
        ),
        migrations.AddField(
            model_name='likecommentproblemmodel',
            name='user',
            field=models.ManyToManyField(related_name='like_comment_problem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeoffermodel',
            name='user',
            field=models.ManyToManyField(related_name='like_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeproblemmodel',
            name='user',
            field=models.ManyToManyField(related_name='like_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeoffermodel',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.offermodel'),
        ),
        migrations.AddField(
            model_name='commentoffermodel',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='post.offermodel'),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likeproblemmodel',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.problemmodel'),
        ),
        migrations.AddField(
            model_name='commentproblemmodel',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='post.problemmodel'),
        ),
    ]
