# Generated by Django 5.1.2 on 2024-10-08 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_offermodel_description_ru_offermodel_title_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problemmodel',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LikeCommentOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_commnet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.commentoffermodel')),
                ('user', models.ManyToManyField(related_name='like_comment_offer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like Offer Comment',
                'verbose_name_plural': 'Like Offer Comments',
            },
        ),
        migrations.CreateModel(
            name='LikeCommentProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.commentproblemmodel')),
                ('user', models.ManyToManyField(related_name='like_comment_problem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like Problem Comment',
                'verbose_name_plural': 'Like Problem Comments',
            },
        ),
        migrations.CreateModel(
            name='LikeOfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.offermodel')),
                ('user', models.ManyToManyField(related_name='like_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like Offer',
                'verbose_name_plural': 'Like Offers',
            },
        ),
        migrations.CreateModel(
            name='LikeProblemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.problemmodel')),
                ('user', models.ManyToManyField(related_name='like_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like Problem',
                'verbose_name_plural': 'Like Problems',
            },
        ),
    ]
