# Generated by Django 5.1.2 on 2024-10-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_offermodel_total_views_problemmodel_total_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='problemmodel',
            name='title_uz',
        ),
    ]
