# Generated by Django 5.1.2 on 2024-10-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_problemmodel_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecommentoffermodel',
            old_name='offer_commnet',
            new_name='offer_comment',
        ),
    ]
