# Generated by Django 5.1.2 on 2024-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='About Title')),
                ('title_en', models.CharField(max_length=128, null=True, verbose_name='About Title')),
                ('title_uz', models.CharField(max_length=128, null=True, verbose_name='About Title')),
                ('description', models.TextField(verbose_name='About Description')),
                ('description_en', models.TextField(null=True, verbose_name='About Description')),
                ('description_uz', models.TextField(null=True, verbose_name='About Description')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=128, verbose_name='Question')),
                ('question_en', models.CharField(max_length=128, null=True, verbose_name='Question')),
                ('question_uz', models.CharField(max_length=128, null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('answer_uz', models.TextField(null=True, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
