# Generated by Django 5.1.2 on 2024-10-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='About Description'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='About Title'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='question_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Question'),
        ),
    ]
