# Generated by Django 5.1.2 on 2024-10-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_aboutmodel_description_zh_aboutmodel_title_zh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='description_zh',
            new_name='description_ch',
        ),
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='title_zh',
            new_name='title_ch',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='answer_zh',
            new_name='answer_ch',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='question_zh',
            new_name='question_ch',
        ),
    ]
