# Generated by Django 5.1.2 on 2024-10-12 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_description_zh_aboutmodel_description_ch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='description_ch',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='title_ch',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='answer_ch',
        ),
        migrations.RemoveField(
            model_name='questionmodel',
            name='question_ch',
        ),
    ]
