name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger workflow on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/exam-6:latest  # Use a relevant Docker image name

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.11
      with:
        host: 138.197.184.77  # Replace with your server IP
        username: root  # Replace with your server username
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Ensure the Docker network exists
          docker network inspect exam_network >/dev/null 2>&1 || docker network create exam_network

          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKERHUB_USER }}/exam-6:latest

          # Stop and remove the old container if it exists
          docker ps -q --filter "name=exam_6" | grep -q . && docker stop exam_6 && docker rm exam_6

          # Run the new container
          docker run -d --name exam_6 \
            --env-file /root/exam_6/.env \  # Update to your actual .env file location if different
            --network=exam_network \
            --restart=always \
            ${{ secrets.DOCKERHUB_USER }}/exam-6:latest \
            sh -c "alembic upgrade head && pybabel compile -d locale -D lang && python main.py"

          # Optional: Display logs for debugging
          sleep 5
          docker logs exam_6
