name: Deploy Application

on:
  workflow_dispatch:
    branches:
      - master  # Adjust to your default branch if needed

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Match your project’s Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test  # Adjust if you have specific test commands

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key in GitHub Secrets
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" | ssh-add -
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << EOF
          cd /path/to/project  # Replace with your project path on the server
          git pull origin main
          source venv/bin/activate  # Adjust if using a virtual environment
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart your-app.service  # Adjust for your service
        EOF
